# Site settings
name: Phuc Phan
title: Phuc Phan | NLP Enthusiast
description: NLP enthusiast focused on large language models and code generation.
url: https://pphuc25.github.io/
baseurl: ''
email: heraclex12@gmail.com
cover: https://pphuc25.github.io/img/og.png
logo: https://pphuc25.github.io/img/emojis/technologist.png
resume: https://pphuc25.github.io/PhanVanPhuc-resume.pdf
social:
  - title: email
    url: mailto:phanphuc1100@gmail.com
  # - title: twitter
  #   url: https://twitter.com/tth_razent
  - title: github
    url: https://github.com/pphuc25
  - title: linkedin
    url: https://www.linkedin.com/in/pphuc

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
